# Generated by Django 5.1.6 on 2026-06-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_phone_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True after the user has verified their email or phone OTP.'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of failed OTP verification attempts. Locked at 5.'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_method',
            field=models.CharField(default='email', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number e.g. +254712345678', max_length=15, null=True, unique=True),
        ),
    ]
