# Generated by Django 5.1.6 on 2026-07-24 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_out', '0002_leaveout_returned_at_leaveout_returned_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ContactAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('call', 'Phone Call'), ('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='call', max_length=20)),
                ('contact_person', models.CharField(help_text='Person or phone number contacted', max_length=100)),
                ('outcome', models.CharField(choices=[('no_answer', 'No Answer'), ('spoke_with_parent', 'Spoke with Parent/Guardian'), ('left_voicemail', 'Left Voicemail'), ('unreachable', 'Unreachable / Line Busy'), ('wrong_number', 'Wrong Number'), ('resolved', 'Issue Resolved')], default='no_answer', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_attempts', to='leave_out.leaveout')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Attempt',
                'verbose_name_plural': 'Contact Attempts',
                'db_table': 'leave_contact_attempt',
                'ordering': ['-created_at'],
            },
        ),
    ]
