# Generated by Django 5.1.6 on 2026-07-24 10:17

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_grade_student_stream'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ['-is_primary', 'priority', 'id'], 'verbose_name': 'Emergency Contact', 'verbose_name_plural': 'Emergency Contacts'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag to retain history'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Priority order (1=highest)'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text='Parent or guardian user accounts linked to this student.', related_name='children_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
