# Generated by Django 5.1.6 on 2026-08-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_emergencycontact_options_remove_student_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('graduated', 'Graduated'), ('suspended', 'Suspended'), ('eloped', 'Eloped / Missing')], db_index=True, default='active', max_length=20),
        ),
    ]
