# Generated by Django 5.1.6 on 2026-06-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm_name', models.CharField(db_index=True, max_length=100)),
                ('room_number', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('current_occupancy', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'room',
                'unique_together': {('dorm_name', 'room_number')},
            },
        ),
    ]
