# Generated by Django 5.1.6 on 2026-06-18 06:34

import django.db.models.deletion
from django.db import migrations, models


def migrate_rooms_to_dorms(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    Dorm = apps.get_model('rooms', 'Dorm')
    for room in Room.objects.all():
        if getattr(room, 'dorm_name', None):
            dorm, created = Dorm.objects.get_or_create(
                name=room.dorm_name,
                defaults={
                    'number_of_rooms': 1,
                    'room_capacity': room.capacity
                }
            )
            if not created:
                dorm.number_of_rooms += 1
                dorm.save()
            room.dorm = dorm
            room.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('number_of_rooms', models.PositiveIntegerField(default=1)),
                ('room_capacity', models.PositiveIntegerField(default=4)),
            ],
            options={
                'verbose_name': 'Dorm',
                'verbose_name_plural': 'Dorms',
                'db_table': 'dorm',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='dorm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.dorm'),
        ),
        migrations.RunPython(migrate_rooms_to_dorms, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('dorm', 'room_number')},
        ),
        migrations.RemoveField(
            model_name='room',
            name='dorm_name',
        ),
    ]

