# Generated by Django 5.1.6 on 2026-08-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='admin_remarks',
            field=models.TextField(blank=True, help_text='Executive remarks/feedback added by Admin.', null=True),
        ),
    ]
