# Generated by Django 5.1.6 on 2026-06-12 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('absent', 'Absent'), ('excused', 'Excused')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_assignments', to='students.student')),
            ],
            options={
                'db_table': 'duty_assignment',
                'ordering': ['duty_roster__duty_date', 'student__full_name'],
            },
        ),
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateField(db_index=True)),
                ('dorm_name', models.CharField(max_length=100)),
                ('task', models.CharField(choices=[('dorm_cleaning', 'Dormitory Cleaning'), ('bathroom', 'Bathroom Cleaning'), ('corridor', 'Corridor Sweeping'), ('common_room', 'Common Room Cleaning')], max_length=50)),
                ('shift', models.CharField(choices=[('morning', 'Morning (4:30 AM - 5:00 AM)'), ('day', 'Daytime (10:00 AM - 2:00 PM)')], max_length=20)),
                ('supervisor', models.CharField(blank=True, help_text='Prefect or senior student in charge', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_students', models.ManyToManyField(related_name='duties', through='duty_roster.DutyAssignment', to='students.student')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_duties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duty Roster',
                'verbose_name_plural': 'Duty Rosters',
                'db_table': 'duty_roster',
                'ordering': ['duty_date', 'dorm_name', 'task'],
                'unique_together': {('dorm_name', 'duty_date', 'task')},
            },
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='duty_roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='duty_roster.dutyroster'),
        ),
        migrations.AlterUniqueTogether(
            name='dutyassignment',
            unique_together={('duty_roster', 'student')},
        ),
    ]
